import { COLORS, colors } from "@/constants/Colors";


export const Coffee = [{
    name: "Coffee",
    description: "A rich and aromatic beverage made from roasted coffee beans.",
    category: "veg",
    nutritionInfo: { kcal: "120", protein: "2g", carbs: "10g", fat: "0g" },
    price: { large: { discounted: 150, original: 180 } },
    url: require("@/assets/images/coffee.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
},
{
    name: "Latte",
    description: "A creamy coffee drink made with espresso and steamed milk.",
    category: "veg",
    nutritionInfo: { kcal: "180", protein: "6g", carbs: "15g", fat: "5g" },
    price: { large: { discounted: 180, original: 200 } },
    url: require("@/assets/images/latte.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
},
{
    name: "Americano",
    description: "A classic coffee drink made by diluting espresso with hot water.",
    category: "veg",
    nutritionInfo: { kcal: "80", protein: "1g", carbs: "5g", fat: "0g" },
    price: { large: { discounted: 120, original: 140 } },
    url: require("@/assets/images/americano.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
},
{
    name: "Vietnamese Coffee",
    description: "A strong and sweet coffee brewed with a traditional Vietnamese drip.",
    category: "veg",
    nutritionInfo: { kcal: "200", protein: "3g", carbs: "20g", fat: "2g" },
    price: { large: { discounted: 200, original: 220 } },
    url: require("@/assets/images/vietCoffee.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
},
{
    name: "Iced Coffee",
    description: "A refreshing coffee drink served over ice.",
    category: "veg",
    nutritionInfo: { kcal: "100", protein: "2g", carbs: "8g", fat: "0g" },
    price: { large: { discounted: 130, original: 150 } },
    url: require("@/assets/images/coldCoffee.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
},
];

export const Tea = [{
    name: "Masala Chai",
    description: "A rich and aromatic beverage made from a blend of spices and tea.",
    category: "veg",
    nutritionInfo: { kcal: "120", protein: "2g", carbs: "10g", fat: "0g" },
    price: { large: { discounted: 150, original: 180 } },
    url: require("@/assets/images/coffee.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
},
{
    name: "Green Tea",
    description: "A light and refreshing beverage made from unoxidized tea leaves.",
    category: "veg",
    nutritionInfo: { kcal: "0", protein: "0g", carbs: "0g", fat: "0g" },
    price: { large: { discounted: 150, original: 180 } },
    url: require("@/assets/images/greenTea.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
},
{
    name: "Tea 1",
    description: "A rich and aromatic beverage made from roasted coffee beans.",
    category: "veg",
    nutritionInfo: { kcal: "120", protein: "2g", carbs: "10g", fat: "0g" },
    price: { large: { discounted: 150, original: 180 } },
    url: require("@/assets/images/coffee.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
},
{
    name: "Tea 2",
    description: "A rich and aromatic beverage made from roasted coffee beans.",
    category: "veg",
    nutritionInfo: { kcal: "120", protein: "2g", carbs: "10g", fat: "0g" },
    price: { large: { discounted: 150, original: 180 } },
    url: require("@/assets/images/coffee.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
},
{
    name: "Tea 3",
    description: "A rich and aromatic beverage made from roasted coffee beans.",
    category: "veg",
    nutritionInfo: { kcal: "120", protein: "2g", carbs: "10g", fat: "0g" },
    price: { large: { discounted: 150, original: 180 } },
    url: require("@/assets/images/coffee.png"),
    color: COLORS.primary500,
    gradientFrom: COLORS.primary100,
    gradientVia: COLORS.primary300,
    gradientTo: COLORS.primary400,
}]
